name: Basics
version: '${project.version}'
main: dev.jordgubbe.basics.Basics
api-version: 1.18
authors: [ jordgubbe ]
description: A worse version of essentials

# Commands
commands:
  basics:
    description: The core command of this plugin
    usage: /basics
  clearlag:
    description: Deletes floating items on the ground that cause lag
    usage: /clearlag
    aliases: cl
  material:
    description: An easier to use version of the vanilla /give command
    usage: /material | item  -[ type of material ]- -[ amount of material ]-
    aliases: item
  vanish:
    description: Used to vanish from other players
    usage: /vanish
  lore:
    description: test
    usage: /lore
  enchant:
    description: Enchant
    usage: /enchant

# Permissions
permissions:
  basics.*:
    description: Permission for players who are OP
    children:
      basics.player: true
      basics.admin: false
  basics.player:
    description: The default permission for the plugin
    default: not op
  basics.admin:
    description: Same as the basics.*, just wanted to make it's own node
    default: op